server:
 port: 9001
 
spring:
 application:
  name: HOUSE MANAGEMENT
 datasource:
  password: Skgfdut5
  url: jdbc:postgresql://localhost:5432/housemgmt
  username: postgres
 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher
  
domainPackage: com.example.house_management.model